crudapp/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("personalprofile.urls"), name="personalprofile"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("oauth/", include("social_django.urls", namespace="social")),
]

personalprofile/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = "personalprofile"

urlpatterns = [
    path(
        "",
        login_required(views.IndexView.as_view(), login_url="/login/"),
        name="index",
    ),
    path(
        "accounts/profile/",
        login_required(views.IndexView.as_view(), login_url="/login/"),
        name="profile",
    ),
    path(
        "add/",
        login_required(views.AddView.as_view(), login_url="/login/"),
        name="add",
    ),
    path(
        "edit/<int:pk>/",
        login_required(views.EditView.as_view(), login_url="/login/"),
        name="edit",
    ),
    path(
        "delete/<int:pk>/",
        login_required(views.DeleteView.as_view(), login_url="/login/"),
        name="delete",
    ),
]

personalprofile/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField


class PersonalProfile(models.Model):
    username = models.CharField(max_length=200)
    fullname = models.CharField(max_length=200, null=True)
    address = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    description = models.TextField(null=True)
    phone_no = PhoneNumberField(blank=True, unique=True)
    additional_info = models.TextField(null=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = "personal_profile"

    def get_absolute_url(self):
        return reverse("personalprofile:info", args=[self.id])

    def __str__(self):
        return self.username

personalprofile/views.py
import json

from django.urls import reverse_lazy
from django.views import generic

from .models import PersonalProfile
from .utils import get_github_profile


class IndexView(generic.ListView):
    model = PersonalProfile
    template_name = "index.html"


class AddView(generic.CreateView):
    model = PersonalProfile
    fields = ["name"]
    template_name = "add.html"
    fields = "__all__"
    success_url = reverse_lazy("personalprofile:index")

    def get(self, request, *args, **kwargs):
        """Override the default get request to set initial values
        in the form. Once this is set we call super.get to return the template
        ."""
        username = self.request.user
        profile = get_github_profile(username=username)
        self.initial = {
            "username": username,
            "fullname": profile.get("name"),
            "description": profile.get("bio"),
            "email": profile.get("email"),
            "additional_info": json.dumps(profile, indent=4),
        }
        return super().get(request, *args, **kwargs)


class EditView(generic.UpdateView):
    model = PersonalProfile
    fields = ["name", "pk"]
    template_name = "edit.html"
    fields = "__all__"
    pk_url_kwarg = "pk"
    success_url = reverse_lazy("personalprofile:index")


class DeleteView(generic.DeleteView):
    model = PersonalProfile
    template_name = "confirm-delete.html"
    pk_url_kwarg = "pk"
    success_url = reverse_lazy("personalprofile:index")

templates/add.html
{% extends 'base.html' %} {% load widget_tweaks %} {% block content %}
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <form method="post">
        {{ form|bulma }}
        {% csrf_token %} {% for field in form.visible_fields %}
        <div class="form-group">
          <label for="{{field.id_for_label}}">{{field.label}}</label>
          {{field|add_class:'form-control'}} {% for error in field.errors %}
          <span class="help-block">{{error}}</span>
          {% endfor %}
        </div>
        {% endfor %}
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Submit</button>
          <a href="{% url 'personalprofile:index' %}" class="btn btn-primary">Cancel</a>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
</head>
<header>{% include 'navbar.html' %}</header>

<body>
  {% if user.is_authenticated %} {% endif %}
  <div class="container">
    <div class="row">{% block content %} {% endblock %}</div>
  </div>
</body>

</html>

templates/confirm-delete.html
{% extends 'base.html' %} {% load widget_tweaks %} {% block content %}
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <form method="post">
        {% csrf_token %}
        <p>Delete {{object}}?</p>
        <div class="form-group">
          <button type="submit" class="button is-primary">Submit</button>
          <a href="{% url 'personalprofile:index' %}" class="button is-danger">Cancel</a>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/edit.html
{% extends 'base.html' %} {% load widget_tweaks %} {% block content %}
<!-- <div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <form method="post">
        {% csrf_token %} {% for field in form.visible_fields %}
        <div class="form-group">
          <label for="{{field.id_for_label}}">{{field.label}}</label>
          {{field|add_class:'form-control'}} {% for error in field.errors %}
          <span class="help-block">{{error}}</span>
          {% endfor %}
        </div>
        {% endfor %}
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Submit</button>
          <a href="{% url 'personalprofile:index' %}" class="btn btn-primary">Cancel</a>
        </div>
      </form>
    </div>
  </div>
</div> -->
<div class="field">
  <form method="post">
    {% csrf_token %} {% for field in form.visible_fields %}
    <label class="label">{{field.label}}</label>
    <div class="control">
      {{field|add_class:'input'}}
      {% for error in field.errors %}
      <span class="help-block">{{error}}</span>
    </div>
    {% endfor %}
    {% endfor %}
    <div class="field is-grouped mt-2">
      <div class="control">
        <button class="button is-link">Submit</button>
      </div>
      <div class="control">
        <a href="{% url 'personalprofile:index' %}" class="button is-danger">Cancel</a>
      </div>
    </div>
  </form>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  {% if object_list.values %} {% for item in object_list %}
  <div class="notification is-primary content is-medium">
    <h5 class="card-title">{{item.username}}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{item.fullname}}</h6>
    <p class="card-text"><strong>E-mail:</strong> {{item.email}}</p>
    <p class="card-text">
      <strong>Phone number:</strong> {{item.phone_no}}
    </p>
    <p class="card-text"><strong>Address:</strong> {{item.address}}</p>
    <p class="card-text"><strong>Bio:</strong> {{item.description}}</p>
    <!-- Profile options -->
    <div class="buttons">
      <a href="{% url 'personalprofile:edit' item.id %}" class="button is-info">Edit</a>
      <a href="{% url 'personalprofile:delete' item.id %}" class="button is-danger">Delete</a>
    </div>
  </div>
</div>
{% endfor %} {% else %}
<h1>No profile created yet</h1>
<a href="/add">Click here to add one</a>
{% endif %}
</div>

{% endblock %}

templates/navbar.html
<nav class="navbar" role="navigation" aria-label="main navigation">
  {% if user.is_authenticated %}
  <div class="navbar-brand">
    <a class="navbar-item" href="/"> Hello, {{user.username}}! </a>
  </div>
  {% else %}
  <div class="navbar-menu">
    <div class="navbar-start">
      <a href="{% url 'social:begin' 'github' %}" class="navbar-item" href="#">
        Sign in
      </a>
      {% endif %}
      <ul class="navbar-item">
        {% if user.is_authenticated %}
        <li>
          <a href="/logout" class="button is-danger">Logout</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>